# ---------------
# Todo: mode: light | dark | auto
mode: light # now only light

# Theme color for customize
# Notice: color value must in double quotes: "#000000"
colors:
  primary: "#5eb7b7"
  # primary: "#6200ee"
  # bg: "#EEEEEE"
  selection_bg: "#96d1c7"
  # tag_start_color:
  # tag_end_color:

# Favicon
# ---------------
favicon: https://wx2.sbimg.cn/2020/04/17/favicon.jpg

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

# Posts / Categories / Tags in sidebar.
sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 1rem center

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•

# Social Links.
social:
  - name: GitHub
    link: https://github.com/kumybryce
    icon: icon-github-line
    color: "#181717"
  - name: ç äº‘éƒ¨ç½²çš„åšå®¢åœ°å€
    link: https://kumybryce.gitee.io/myblog/
    icon: iconboke
  - name: ç äº‘
    link: https://gitee.com/kumybryce
    icon: iconmayun
# Extra links
pages:
  - name: cssè§‚èµ
    url: http://www.xinhongjiseu.club/page-mypage.html
    icon: icon-genderless-line
    color: "#efa8e4"
  - name: color hunté…è‰²ç½‘ç«™
    url: https://colorhunt.co/
    icon: iconcolor
    color: "#de7fab"
  - name: leancloudè¯„è®ºç®¡ç†
    url: https://leancloud.cn/dashboard/data.html?appid=ENnEcdGIT16rS84XB1Oz0cwN-gzGzoHsz#/
    icon: icondatabase
    color: "#de7fab"
  - name: å…¬ç›Šå›¾åºŠ
    url: https://sbimg.cn/
    icon: iconxitonggongju-tuchuanggongju
    color: 
  - name: å°ç ´ç«™
    url: https://www.bilibili.com/
    icon: iconwf_Bzhan
    color: 
  - name: ä¸­å›½å¤§å­¦æ…•è¯¾
    url: https://kaoyan.icourse163.org/
    icon: icontubiaozhizuomoban
    color: 
  - name: MSDN
    url: https://msdn.itellyou.cn/
    icon: iconxitong
    color: 
  - name: é¸ æ‘©æœç´¢å›¾ä¹¦
    url: https://www.jiumodiary.com/
    icon: icontushu2
    color: 
  - name: smallpdf
    url: https://smallpdf.com/cn
    icon: iconpdf
    color: 
  - name: wordä¸­çš„ä»£ç æ ¼å¼åŒ–
    url: http://www.planetb.ca/syntax-highlight-word
    icon: icondaima
    color: 
  - name: å°çŒ´å·ç±³
    url: https://myseu.cn/
    icon: iconxiaohou
    color: "#77d8d8#
  - name: gitç®€ä»‹
    url: https://www.liaoxuefeng.com/wiki/896043488029600/896067008724000
    icon: icongit
    color: 
  - name: 3D Demo
    url: https://edwardzhong.github.io/sites/demo/index.html
    icon: iconicon-test
    color: 
  - name: coursera
    url: https://www.coursera.org/search?query=andrew%20ng&isNewUser=true
    icon: iconcoursera
    color: 
  - name: çˆ±ç»™ç½‘
    url: http://www.aigei.com/
    icon: icongei
    color: 
  - name: é˜¿é‡Œå·´å·´çŸ¢é‡å›¾æ ‡
    url: https://www.iconfont.cn/
    icon: iconiconfont
    color: "#ff6363"
  - name: å›¾æ ‡è½¬æ¢Convertio
    url: https://convertio.co/
    icon: iconzhuanhuan
    color: 
# pages
# -------
# friend
anonymous_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/avatar/none.jpg

girls:
  enable: false

banner:
  enable: true
  title: å±±å±±çš„æ‰å‘å†ç¨‹
  src: /js/ui/banner.js

# Sidebar Avatar
avatar:
  enable: true
  url: /img/favicon.jpg
  # If true, the avatar would be dispalyed in circle.
  rounded: true
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1
  mickey_mouse: false

# main menu navigation
menu:
  home:
    path: /
    icon: icon-home-4-line
  archives:
    path: /archives
    icon: icon-archive-line
  tags:
    path: /tags
    icon: icon-price-tag-3-line
  categories:
    path: /categories
    icon: icon-folder-2-line
  custom:
    title: æ–‡æ¡£
    path: https://yun.yunyoujun.cn
    icon: icon-settings-line

# archive
archive:
  last_word: æ²¡æœ‰æ›´å¤šçš„é»‘å†å²äº†_(:Ğ·ã€âˆ )_

# https://github.com/MikeCoder/hexo-tag-cloud
tag_cloud:
  enable: false
  width: 300
  height: 300

# You can set color for every tag or category.
tags:
  Python: "#ff6363"
  é€šä¿¡: "#ff6363"
  ç³»ç»Ÿ: "#97e5ef"
  Linux: "#efa8e4"
  Qt: "#f8e1f4"
  opencv: "#efa8e4"
  

categories:
  ç¯å¢ƒé…ç½®: dimgray
  ç¼–ç¨‹: dimgray
  ä¸“ä¸šè¯¾: dimgray

# post type
types:
  bilibili:
    color: "#FF8EB3"
    icon: icon-bilibili-line
  github:
    color: black
    icon: icon-github-line
  link:
    color: blue
    icon: icon-external-link-line

# post_card
post_card:
  opacity: 0.9

# link
# -------
preload:
  style:
    - /css/hexo-theme-yun.css
  script:
    - /js/utils.js
    - /js/hexo-theme-yun.js

prefetch:
  # style:
  #   - /css/prism.css
  script:
    - /js/sidebar.js

dns_prefetch:
  # - https://xxx

# do more(TCP handshake...) than dns-fetch
preconnect:
  - https://cdn.jsdelivr.net

# img loading="lazy"
lazyload:
  enable: true

# stylesheets loaded in the <head>
css:
  - /css/hexo-theme-yun.css

# scripts loaded in the end of the body
js:
  - /js/utils.js
  - /js/hexo-theme-yun.js

# custom your assets in head
head:
  css:
  js:
    base: 
    async: 
      iconfont: //at.alicdn.com/t/font_1763255_y9klqsvfr3b.js
    defer:

# cdn for third-party library (always include)
cdn:
  pre: ""
  # pre: https://cdn.jsdelivr.net/gh/YunYouJun/yunyoujun.github.io
  css:
  # font
  # font: https://fonts.googleapis.com/css?family=Open+Sans:300&display=swap
  # font: https://fonts.loli.net/css?family=Montserrat
  # icon
  # material-design-icons: https://fonts.googleapis.com/icon?family=Material+Icons+Outlined
  # markdown
  # github-markdown-css: https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/3.0.1/github-markdown.min.css
  # star-markdown-css: https://cdn.jsdelivr.net/npm/star-markdown-css/dist/planet/planet-markdown.min.css
  # blood-markdown-css: https://cdn.jsdelivr.net/npm/star-markdown-css/dist/blood/blood-common.min.css
  js:
    base:
    async:
      iconfont: //at.alicdn.com/t/font_1140697_9juba7x0cw.js
    defer:

# cdn for third-party library (alternative include)
vendors:
  algolia_search: https://cdn.jsdelivr.net/npm/algoliasearch@4/dist/algoliasearch-lite.umd.js
  instant_search: https://cdn.jsdelivr.net/npm/instantsearch.js@4/dist/instantsearch.production.min.js
  anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
  valine_js: https://cdn.jsdelivr.net/npm/valine@latest/dist/Valine.min.js
  minivaline_js: https://cdn.jsdelivr.net/npm/minivaline/dist/MiniValine.min.js
  scrollreveal: https://cdn.jsdelivr.net/npm/scrollreveal/dist/scrollreveal.min.js
  katex:
    js: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js
    css: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
    auto_render: https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/auto-render.min.js
    copy_tex:
      css: https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.min.css
      js: https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.min.js
  aplayer:
    #css: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.css
    #js: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.js
    #meting: https://cdn.jsdelivr.net/npm/meting@1/dist/Meting.min.js
    #js: https://cdn.bootcss.com/aplayer/1.10.1/APlayer.min.js
   # meting: https://cdn.jsdelivr.net/npm/meting@1.2.0/dist/Meting.min.js
    #css: https://cdn.bootcss.com/aplayer/1.10.1/APlayer.min.css
  trianglify: https://cdn.jsdelivr.net/npm/trianglify@latest/dist/trianglify.min.js
  fireworks: /js/ui/fireworks.js
  search: /js/search/index.js
  sidebar: /js/sidebar.js

# UI
# custom your color in colors
fireworks:
  enable: false
  colors:
    - "151,229,239"
    - "255,240,245"
    - "248,225,244"
    # - '3, 28, 95'
    # - '0, 8, 55'

# https://github.com/qrohlf/trianglify
trianglify:
  enable: false
  cell_size: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/kumybryce/resource@v1.102/mycdn/cur/Arrow.cur
  pointer: https://cdn.jsdelivr.net/gh/kumybryce/resource@v1.102/mycdn/cur/Hand.cur
  text: https://cdn.jsdelivr.net/gh/kumybryce/resource@v1.102/mycdn/cur/IBeam.cur

smoothScroll: true

# You can see effect in https://scrollrevealjs.org/
scrollreveal: true

bg_image:
  enable: false
  url: https://wx1.sbimg.cn/2020/04/17/desk111.jpg # recomend image related to your mode
  #blur: 5px
  opacity: 0.8

# Reward (Donate)
reward_settings:
  # If true, reward would be displayed in every posts and pages by default.
  # You can show or hide reward in a specific page throuth `reward: true | false` in Front Matter.
  enable: true
  icon: icon-hand-coin-line
  comment: ä¼¸æ‰‹è¦é’±ğŸ’°ä¹°ç”Ÿå‘è¯æ°´
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96

reward:
  - name: æ”¯ä»˜å®
    path: https://wx1.sbimg.cn/2020/04/17/qq_pic_merged_1587074686756.jpg
    color: "#00A3EE"
    icon: icon-alipay-line
  - name: å¾®ä¿¡æ”¯ä»˜
    path: https://wx1.sbimg.cn/2020/04/17/qq_pic_merged_1587074775997.jpg
    color: "#2DC100"
    icon: icon-wechat-pay-line
  # - name: paypal
  #   link: https://paypal.com
  #   path: https://www.paypalobjects.com/images/shared/paypal-logo-129x32.svg
  #   color: "#2D70B5"
  #   icon: icon-paypal-line

# Creative Commons 4.0 International License.
# https://creativecommons.org/licenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.fr, deed.de, etc.
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true

# AddThis Share, See: https://www.addthis.com
# Go to https://www.addthis.com/dashboard to customize your tools.
# add_this_id:

# Post edit
# Dependencies: https://github.com/hexojs/hexo-deployer-git
post_edit:
  enable: false
  url: https://gitee.com/kumybryce/myblog/2020 # Link for view source.

# Footer Settings
# ---------------
footer:
  since: 2020

  # Icon between year and copyright info.
  icon:
    # `heart` is recommended with animation in red (#ff0000).
    name: icon-cloud-line
    # If you want to animate the icon, set it to true.
    animated: true
    # Change the color of icon, using Hex Code.
    color: "#0078E7"

  powered:
    # Hexo link (Powered by Hexo).
    enable: true
    # Version info of Hexo after Hexo link (vX.X.X).
    version: true

  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # http://www.beian.miit.gov.cn
  beian:
    enable: false
    # icp: è‹ICPå¤‡xxxxxxxxå·

  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2020-02-24T15:19:00"

  # Any custom text can be defined here.
  # custom_text: Hosted by <a href="https://pages.coding.me" rel="noopener" target="_blank">Coding Pages</a>

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

# notice pin board
notice:
  enable: false
  content: Thanks for watching my blog.

# third party
# ----------------

# say something
# https://say.elpsy.cn
say:
  enable: true
  # api: https://say.elpsy.cn/sentences.json
  # /data/sentences.json
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # src is the script
  src: /js/say.js
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn
    # api: https://v1.hitokoto.cn?c=a&c=b&c=c&c=d&c=k

# you can new JSON file in your blog root folder
# example: source/data/sentences.json
# then set say.api: /data/sentences.json
# https://say.elpsy.cn
# [
#   {
#     "content": "Hello, World!",
#     "author": "Brian Kernighan",
#     "from": "The C Programming Language"
#   },
#   {
#     "content": "æˆ‘ä»¬ä¸€æ—¥æ—¥åº¦è¿‡çš„æ‰€è°“æ—¥å¸¸ï¼Œå®é™…ä¸Šå¯èƒ½æ˜¯æ¥è¿ä¸æ–­çš„å¥‡è¿¹ã€‚",
#     "from": "æ—¥å¸¸"
#   },
#   {
#     "content": "æ˜¯å•Šï¼Œæˆ‘æ‰€çˆ±çš„ï¼Œå³éç¾¤æ˜Ÿï¼Œä¹Ÿéé“¶æ²³ã€‚",
#     "author": "äº‘æ¸¸å›",
#     "from": "yunyoujun.cn"
#   },
#   {
#     "content": "éšçº¦é›·é¸£ é˜´éœ¾å¤©ç©º ä½†ç›¼é£é›¨æ¥ èƒ½ç•™ä½ åœ¨æ­¤",
#     "from": "ä¸‡å¶é›†Â·é›·ç¥çŸ­æ­Œ"
#   }
# ]

# Comments
# -------
comment:
  enable: true
  tips:
    - è‹¥æ‚¨æ—  GitHub è´¦å·ï¼Œå¯ç›´æ¥åœ¨ä¸‹æ–¹åŒ¿åè¯„è®ºã€‚

# GitHub Issues Link Button
# https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests
github_issues:
  enable: false
  username: YunYouJun
  repository: yunyoujun.github.io
  filters: is:issue

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  enable: true
  appId: ENnEcdGIT16rS84XB1Oz0cwN-gzGzoHsz
  appKey: 4eP69Ir5FxFhWy92iiR1QEUq
  serverURLs:
  # another choice: https://github.com/DesertsP/Valine-Admin
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: æ¥å‘€ï¼å¿«æ´»å‘€ï¼o(*ï¿£â–½ï¿£*)o # comment box placeholder
  avatar: # gravatar style
  meta: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
  visitor: true
  visitor_index: false

# MiniValine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://github.com/MiniValine/MiniValine
minivaline:
  enable: false
  appId: # Your leancloud application appid
  appKey: # Your leancloud application appkey
  placeholder: Write a Comment # Comment box placeholder
  adminEmailMd5: # The MD5 of Admin Email to show Admin Flag.
  math: true # Support MathJax.
  md: true # Support Markdown.
  # MiniValine's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en  | zh-CN | (and many more)
  # More i18n info: https://github.com/MiniValine/minivaline-i18n
  lang:

# Show Views / Visitors of the website / page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi
busuanzi:
  enable: false
  site_uv: true
  site_uv_icon: icon-user-line
  site_pv: true
  site_pv_icon: icon-eye-line
  page_pv: true
  page_pv_icon: icon-eye-line

# Post wordcount display settings
# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  item_text_post: true
  item_text_total: true
  awl: 2
  wpm: 275

# search
search:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
  placeholder: æƒ³è¦æœäº›ä»€ä¹ˆï¼Ÿ

engine_search:
  enable: false
  #href: "https://www.google.com/search?q=site:"
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: yunyoujun.cn

# https://github.com/wzpan/hexo-generator-search
local_search:
  enable: true
  src: /js/search/local-search.js

# https://github.com/oncletom/hexo-algolia
algolia_search:
  enable: false
  src: /js/search/algolia-search.js
  hits:
    per_page: 8 # the number of search results per page
# Ads
# ---------------
# Google Adsense
google_adsense:
  enable: false
  client: ca-pub-2245427233262012

# Analysis
# ---------------
google_analytics:
  enable: false
  id: UA-163860217-1

# math fomula
# https://katex.org/
katex:
  copy_tex: true
  global: true

# plugins
aplayer:
  meting: true
  asset_inject: false

# special
mourn:
  enable: true
  days:
    - "4-4"
    - "5-12"
    - "9-18"
# SEO
# https://ziyuan.baidu.com/linksubmit/index
baidu_push: false

